---
title: "Jekyll Websites"
output:
  html_document:
    toc: true
    include:
      after_body: footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Jekyll is another simple and popular way to make websites.  There are many templates on GitHub that you can copy (fork) to make your own website.  


# jekyll-simple-blog

This code is from [M Koehnke](http://mkoehnke.github.io).  Per M Koehnke: This is an anonymized version of [Chris Eidhof's](http://github.com/chriseidhof) brilliant [blog theme](http://github.com/chriseidhof/chris.eidhof.nl) converted from Cactus to Jekyll.

A live demo can be found [here](http://rverse-tutorials.github.io/jekyll-simple-blog/).

Go to the [RVerse-Tutorials\jekyll-simple-blog](https://github.com/RVerse-Tutorials/jekyll-simple-blog) repository and click the Fork button in the upper right.  You will need to be logged into your GitHub account.  Then open RStudio and create a new project from that repository.  This creates a copy of jekyll-simple-blog that is linked to the copy of the repository that you makde in your  GitHub account.
 
[Watch a video of this step](https://youtu.be/xeeKrGuaFRg)

*INCOIS participants: You will find a copy of the repository in the RWorkflow directory that you copied from the thumb drive. However, without internet you won't be able to build your jekyll website.*

## Making the blog live

* Go to settings of your jekyll-simple-blog GitHub repository and set Github Pages source as master.
* Your new site should be ready at https://yourusername.github.io/jekyll-simple-blog/ . Note it can take awhile (5-10 min) for the website to appear and for changes to appear.
* If you change the name of your repository (meaning change it from jekyll-simple-blog to something else), **change the baseurl in `_config.yml`**

## Making changes

* Edit posts in `_posts`
* Add posts in `_posts`
* Upload the changes to GitHub via GitHub Desktop or Git in RStudio.

# simple-cv

This is a super simple online resume forked from [http://webjeda.com/online-cv/](http://webjeda.com/online-cv/).   [Eli Holmes](https://eeholmes.github.io/) simplified Webjeda's design to make it more suitable for a simple flat resume and make it printable.

## Installation
* Fork the repository https://github.com/RVerse-Tutorials/simple-cv
* Go to settings of your repository and set Github Pages source as master.
* Your new site should be ready at https://username.github.io/simple-cv/
* If you change the name of your repository, change the baseurl in `_config.yml`

## Enter your data
* Edit `_config.yml` with your name, education and summary.  The summary will appear in About Me.
* Edit `_data\experiences.yml` with your work experience.
* Edit `_data\coursework.yml` with your coursework.
* Edit `_data\skills.yml` with your skills.
* Add your picture to `assets\images\` and put the file name in `_config.yml` in `pic:`

