---
title: "Resources"
---

## NOAA affiliated GitHub sites

* [NMFS Openscapes](https://nmfs-openscapes.github.io/)
* [NMFS R User Group](https://nmfs-openscapes.github.io/NMFS-R-UG/)
* [NOAA Fisheries Integrated Toolbox](https://noaa-fisheries-integrated-toolbox.github.io/)

## NOAA Fisheries GitHub Resources

* [FIT Resources](https://github.com/nmfs-fish-tools/Resources) NOAA licences, Disclaimers, code review procedures.
* [FIT Resources blog](https://noaa-fisheries-integrated-toolbox.github.io/resources/) Scroll down the navbar on left to see coding resources.
* [NMFS Palette](https://github.com/nmfs-general-modeling-tools/nmfspalette)
* [pkgdown css for NOAA pkgdown sites](https://github.com/nmfs-general-modeling-tools/nmfspalette/blob/main/pkgdown/extra.css)
* [NMFS Reports](https://emilymarkowitz-noaa.github.io/NMFSReports/) Check out this package by Emily Markowitz at AFSC for making NMFS Reports with proper branding and structure.

## Never worked with R?

If you have never worked with R, you can get a basic familiarity by going through [this free tutorial](https://www.datacamp.com/courses/free-introduction-to-r).  Takes about 4 hours.   

You can also learn R straight from within R using the [swirl package](https://swirlstats.com/).  This doesn't require internet access except to install the package.

Here is another basic R introduction from [ComputerWorld](https://www.computerworld.com/article/2497143/business-intelligence/business-intelligence-beginner-s-guide-to-r-introduction.html).

The book that I recommend for scientists who have never worked with R is [The R Student Companion](https://www.amazon.com/R-Student-Companion-Brian-Dennis-ebook/dp/B009AIU07G) by Brian Dennis. It'll get you up to speed with the type of programming that scientists do with R. I think you'd be fine just renting it for a month and getting through as much as you can in a month. After a few chapters, you'll know your way around R and, more importantly, how to program with functions. Then you'll be ready for something else. 

Once you work through that, [R for Data Science](https://r4ds.had.co.nz/) by Garrett Grolemund
and Hadley Wickham is very good for what the sort of work we do.

# R Markdown

* [RStudio's lessons](https://rmarkdown.rstudio.com/lesson-1.html)

# Git and GitHub

* [Happy Git with R](https://happygitwithr.com/) Detail on Git and GitHub, but accessible.

# R packages that I use all the time

These are some basic packages that I use all the time. This does not include the analysis packages that I use.

* [Tidyverse](https://www.tidyverse.org/) packages. I am not a fan of all the tidyverse package and I dislike piping (because it is horribly slow and I need fast for simulation work), but I try to keep up with the ideas in the "tidyverse" and I try to adopt tidyverse style. In particular, I try to format all my data into tidy format.
* ggplot2: I find ggplot to be hard to learn and too confining, but I use it all the time because it makes plots with many layers so much easier and it makes plot layout easier. I don't like it for my publication quality plots (just too much hassle to get the look I want) but I use it constantly for mock-ups.
* stringr: I work with strings all the time so I always need this.
* dplyr: When I need to go from wide-form to short-form layout, I like it. Definitely I think it is good to inform yourself as to what it does.
* XML: I use it to scrape data from online tables using the `readHTMLTable()` function. I think xml2 in the tidyverse might do the same thing.
* here: This is a handy utility package, along with `file.path()` allows you to make file paths to the base of the project. If you find yourself doing `setwd()` anywhere in your code, you'll want to use `here()` to avoid that because doing that breaks your code for anyone else.
* xtable: Handy for making complex tables.

# Other Reproducible Research Short-Courses

* [Reproductible Research 2017](https://eriqande.github.io/rep-res-eeb-2017/index.html)  Source for some of the introductory material.

# Making simple websites

* [Another tutorial] (https://jules32.github.io/rmarkdown-website-tutorial/index.html) with more examples and slightly more complicated websites.

# Jekyll

* [Installing Jekyll on Mac OS](https://learn.cloudcannon.com/jekyll/install-jekyll-on-os-x/)
* [Jekyll build](https://learn.cloudcannon.com/jekyll/running-jekyll/)

# Jekyll Templates

* [Hugo Academic](https://sourcethemes.com/academic/)  Popular Jekyll template in academia.

# Travis CI (continuous integration)

* https://juliasilge.com/blog/beginners-guide-to-travis/


